### ISSUE TITLE
Glassfish Managed Container fails to start properly

### ISSUE THREAD

**Issue by s1hofmann** [arquillian/arquillian-container-glassfish#39]
I'm currently faced with the problem that my Glassfish Managed Container fails to start properly.

Whenever I'm executing my tests it fails deploy my application with following output:

```
Starting container using command: [java, -jar, /opt/payara41/glassfish/modules/admin-cli.jar, start-domain, domain1, -t]
Successfully started the domain : domain1
domain  Location: /opt/payara41/glassfish/domains/domain1
Log File: /opt/payara41/glassfish/domains/domain1/logs/server.log
Admin Port: 4848
Jul 13, 2017 3:08:40 PM org.jboss.arquillian.container.glassfish.clientutils.GlassFishClientUtil getResponseMap
SEVERE: exit_code: FAILURE, message: An error occurred while processing the request. Please see the server logs for details. [status: SERVER_ERROR reason: Service Unavailable]
```

Looking at the server log I'm assuming it's a class loading problem:

```
java.lang.ClassNotFoundException: org.glassfish.admin.rest.resources.generatedASM.DomainResource not found by org.glassfish.main.admin.rest-service [312]
	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1532)
	at org.apache.felix.framework.BundleWiringImpl.access$400(BundleWiringImpl.java:75)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1955)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.glassfish.admin.rest.adapter.RestManagementResourceProvider.getResourceClasses(RestManagementResourceProvider.java:110)
	at org.glassfish.admin.rest.adapter.RestAdapter.exposeContext(RestAdapter.java:294)
	at org.glassfish.admin.rest.adapter.RestAdapter.service(RestAdapter.java:175)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:466)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:169)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:206)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:180)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:539)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:593)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:573)
	at java.lang.Thread.run(Thread.java:748)
]]
```

After manually starting the server with the exact same command as mentioned in my test output, I'm able to successfully run my tests after connecting to the running server.

I'm on a Linux machine 

    Linux Leger 4.10.0-26-generic #30-Ubuntu SMP Tue Jun 27 09:30:12 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

with Arquillian Glassfish adapter v1.0.1

        <dependency>
            <groupId>org.jboss.arquillian.container</groupId>
            <artifactId>arquillian-glassfish-managed-3.1</artifactId>
            <version>${arquillian.glassfish.version}</version>
            <scope>test</scope>
        </dependency>

in combination with

    payara-4.1.2.172

I'd be grateful for any pointers on this problem!

**Comment by bartoszmajsak** [comment]
Does it work with `1.0.0.Final`?

**Comment by s1hofmann** [comment]
Just checked, same behaviour on 1.0.0.Final as with 1.0.1.

I'll see what I can do about the demo project, but I'll try to set one up.

**Comment by bartoszmajsak** [comment]
Thanks!

**Comment by s1hofmann** [comment]
After some tinkering I realized that this problem seems to be related to our domain configuration.
When deploying to a default domain config, I'm not encountering above problems which leads me to the assumption that our config is causing problems. Will keep reporting back when there are any news on this.

**Comment by s1hofmann** [comment]
The issue was indeed caused by a misconfigured Glassfish. Sorry for the inconviniences.
Closing.

**Comment by bartoszmajsak** [comment]
No worries and thanks for spending time analyzing it. If that is not specific to your project setup would it make sense to share your findings here?

**Comment by s1hofmann** [comment]
From what I experienced, the main cause for my troubles were multiple server configs.
After stripping my domain.xml, leaving it with only one server config, everything started to work.

**Comment by gbuckholtz** [comment]
I have the same problems starting up with payara 4.1.2.174 and it is just the default vanilla install.

This is the where things go wrong when arquillian starts up payara
'''
> [2017-12-06T12:24:09.211-0500] [Payara 4.1] [SEVERE] [] [javax.enterprise.admin.rest] [tid: _ThreadID=62 _ThreadName=admin-thread-pool::admin-listener(2)] [timeMillis: 1512581049211] [levelValue: 1000] [[
>   
> java.lang.ClassNotFoundException: org.glassfish.admin.rest.resources.generatedASM.DomainResource not found by org.glassfish.main.admin.rest-service [300]
> 	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1532)
> 	at org.apache.felix.framework.BundleWiringImpl.access$400(BundleWiringImpl.java:75)
> 	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1955)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> 	at java.lang.Class.forName0(Native Method)
> 	at java.lang.Class.forName(Class.java:264)
> 	at org.glassfish.admin.rest.adapter.RestManagementResourceProvider.getResourceClasses(RestManagementResourceProvider.java:110)
'''

And this is when you use the same command that arquillian created on the command line:

'''
> [2017-12-06T12:24:10.582-0500] [Payara 4.1] [INFO] [NCLS-REST-00001] [javax.enterprise.admin.rest] [tid: _ThreadID=62 _ThreadName=admin-thread-pool::admin-listener(2)] [timeMillis: 1512581050582] [levelValue: 800] [[
>   Listening to REST requests at context: /command/domain.]]
> 
 '''

**Comment by bartoszmajsak** [comment]
Interesting, especially considering the fact that we have some basic tests executed against the same version: https://github.com/arquillian/arquillian-container-glassfish/blob/a383d375efa4799fc62051039cbae88c3cfd9335/glassfish-managed-3.1/pom.xml#L251

Can you share some more details about your setup?

**Comment by gbuckholtz** [comment]
Thanks for pointing me to a sample that works!   I will have a look at that and then I may be able to tell you what the differences are between my install and the working one.

**Comment by bartoszmajsak** [comment]
Yeah please do! It's important for us to make sure this thing work :) So if you have ideas how to harden the test suite it will be just awesome.

**Comment by gbuckholtz** [comment]
As a debugging exercise I modified my arquillian.xml to included the ‘allowConnectingToRunningServer’ and that allowed me to move forward.

I took the latest build of payara and unzipped it.  I did change the name of the root folder from ‘payara41 2’ to be payara412 thinking there could be a problem with spaces at some point.

Oh,  this is the error I get on the maven build:

Starting container using command: [java, -jar, /Users/gbuckholtz/appservs/payara412/glassfish/modules/admin-cli.jar, start-domain, --debug, -t]
Successfully started the domain : domain1
domain  Location: /Users/gbuckholtz/appservs/payara412/glassfish/domains/domain1
Log File: /Users/gbuckholtz/appservs/payara412/glassfish/domains/domain1/logs/server.log
Admin Port: 4848
SEVERE: exit_code: FAILURE, message: An error occurred while processing the request. Please see the server logs for details. [status: SERVER_ERROR reason: Service Unavailable]
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 5.668 sec <<< FAILURE!
Forcing container shutdown using command: [java, -jar, /Users/gbuckholtz/appservs/payara412/glassfish/modules/admin-cli.jar, stop-domain, -t]

Results :

Tests in error: 
  ca.queensu.our.easi.student.selenium.StudentA11nRequestTest: exit_code: FAILURE, message: An error occurred while processing the request. Please see the server logs for details. [status: SERVER_ERROR reason: Service Unavailable]

and the error in the server log is:

[2017-12-06T13:34:47.516-0500] [Payara 4.1] [SEVERE] [] [javax.enterprise.admin.rest] [tid: _ThreadID=63 _ThreadName=admin-thread-pool::admin-listener(2)] [timeMillis: 1512585287516] [levelValue: 1000] [[

java.lang.ClassNotFoundException: org.glassfish.admin.rest.resources.generatedASM.DomainResource not found by org.glassfish.main.admin.rest-service [300]
        at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1532)
        at org.apache.felix.framework.BundleWiringImpl.access$400(BundleWiringImpl.java:75)
        at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1955)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at org.glassfish.admin.rest.adapter.RestManagementResourceProvider.getResourceClasses(RestManagementResourceProvider.java:110)
        at org.glassfish.admin.rest.adapter.RestAdapter.exposeContext(RestAdapter.java:294)
        at org.glassfish.admin.rest.adapter.RestAdapter.service(RestAdapter.java:175)
        at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:483)
        at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:180)
        at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:206)
        at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:180)
        at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
        at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
        at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:539)
        at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.j


Here is the maven snippet for the application:

          <id>arquillian-glassfish-managed</id>
            <properties>
                <runSuite>**/WebFunctionalTestSuite.class</runSuite>

            </properties>
            
            <dependencies>
                <dependency>
                    <groupId>org.jboss.arquillian.container</groupId>
                    <artifactId>arquillian-glassfish-managed-3.1</artifactId>
                    <scope>test</scope>
                </dependency>             
                
                
                <dependency>
                    <groupId>org.jboss.arquillian.junit</groupId>
                    <artifactId>arquillian-junit-container</artifactId>
                    <scope>test</scope>
                </dependency>
            
                <dependency>
                    <groupId>junit</groupId>
                    <artifactId>junit</artifactId>
                    <scope>test</scope>
                </dependency>
            
                <dependency>
                    <groupId>org.jboss.arquillian.graphene</groupId>
                    <artifactId>graphene-webdriver</artifactId>
                    <version>2.3.2</version>
                    <type>pom</type>
                    <scope>test</scope>
                </dependency>
                
    
            </dependencies>

       
            <build>
                <testResources>
                    <testResource>
                        <directory>src/test/resources</directory>
                        <filtering>true</filtering>
                    </testResource>
                    <testResource>
                        <directory>src/test/resources-glassfish-managed</directory>
                    </testResource>
                </testResources>
                <plugins>
                    
                    <plugin>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <version>2.12</version>
                        <configuration>
                            <systemPropertyVariables>
                                <java.util.logging.config.file>
                                    ${project.build.testOutputDirectory}/logging.properties
                                </java.util.logging.config.file>
                                <derby.stream.error.file>
                                    ${project.build.directory}/derby.log
                                </derby.stream.error.file>
                                <arquillian.launch>glassfish-managed</arquillian.launch>
                            </systemPropertyVariables>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>


and the arquillian.xml


    <container qualifier="glassfish-managed">
        <configuration>
            <property name="glassFishHome">/Users/gbuckholtz/appservs/payara412</property>
            <property name="debug">true</property>
            <property name="outputToConsole">true</property>
            <property name="allowConnectingToRunningServer">true</property>
        </configuration>
    </container>

and here is the dependencyManagement dependencies:

           <dependency>
                <groupId>org.jboss.arquillian</groupId>
                <artifactId>arquillian-bom</artifactId>
                <version>1.1.15.Final</version>
                <scope>import</scope>
                <type>pom</type>
            </dependency>
            <dependency>
                <groupId>org.hibernate</groupId>
                <artifactId>hibernate-jpamodelgen</artifactId>
                <version>1.2.0.Final</version>
            </dependency>
            <dependency>
                <groupId>junit</groupId>
                <artifactId>junit</artifactId>
                <version>4.12</version>
            </dependency>
            
            
            
            <dependency>
                <groupId>org.jboss.arquillian.extension</groupId>
                <artifactId>arquillian-drone-bom</artifactId>
                <version>2.4.5</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            
            <dependency>
                <groupId>org.jboss.arquillian.extension</groupId>
                <artifactId>arquillian-rest-warp-bom</artifactId>
                <version>1.0.0.Alpha4</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            
        
            
            <dependency>
                <groupId>org.jboss.arquillian.extension</groupId>
                <artifactId>arquillian-persistence-dbunit</artifactId>
                <version>1.0.0.Alpha7</version>
                <scope>test</scope>
            </dependency>
        
        
            
            <dependency>
                <groupId>org.jboss.arquillian.container</groupId>
                <artifactId>arquillian-glassfish-embedded-3.1</artifactId>
                <version>1.0.1</version>
            </dependency>
            
            
            <dependency>
                <groupId>org.jboss.arquillian.container</groupId>
                <artifactId>arquillian-glassfish-managed-3.1</artifactId>
                <version>1.0.0.CR4</version>
            </dependency>


have I missed anything?

**Comment by gbuckholtz** [comment]
minor update:

I updated the version of arquillian-glassfish-managed-3.1 to be 1.0.2 and I still get the exact same results


     
            <dependency>
                <groupId>org.jboss.arquillian.container</groupId>
                <artifactId>arquillian-glassfish-managed-3.1</artifactId>
                <version>1.0.2</version>
            </dependency>
